//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplomka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couriers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Couriers()
        {
            this.Deliveries = new HashSet<Deliveries>();
        }
    
        public int CourierID { get; set; }
        public string FIO { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string CourierStatus { get; set; }
        public string Password { get; set; }
        public string VehicleType { get; set; }
        public string VehicleRegistrationPlates { get; set; }
    
        public virtual CourierPositions CourierPositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deliveries> Deliveries { get; set; }
    }
}
