//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplomka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public int DeliveryID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> CourierID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string DeliveryStatus { get; set; }
        public string CouriersFio { get => Couriers.FIO; }
    
        public virtual Couriers Couriers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
