//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplomka
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingCost
    {
        public decimal WeightFrom { get; set; }
        public decimal WeightTo { get; set; }
        public decimal Cost { get; set; }
        public Nullable<int> DeliveryTypeID { get; set; }
    
        public virtual DeliveryTypes DeliveryTypes { get; set; }
    }
}
